"""
WAF Detective - fingerprinting and basic detection heuristics
Supports 12 WAF providers with header/cookie/body signature detection.
"""
import asyncio
import logging
from typing import Optional, Dict, Any
from urllib.parse import urljoin

try:
    from typing import TYPE_CHECKING
    if TYPE_CHECKING:
        import aiohttp
    else:
        import aiohttp
except Exception:
    aiohttp = None

logger = logging.getLogger("cerberus.core.waf_detective")

# ─── WAF Fingerprint Database ─────────────────────────────────────────────
WAF_SIGNATURES = [
    # (Name, header_checks: [(header, substring)], cookie_checks: [substring], body_checks: [substring])
    ("Cloudflare", [("server", "cloudflare"), ("cf-ray", "")], ["__cfduid", "__cf_bm"], ["attention required", "cf-chl", "checking your browser"]),
    ("Akamai", [("server", "akamai"), ("x-akamai-transformed", "")], ["ak_bmsc", "akaalb", "akamai"], ["bot manager", "akamai"]),
    ("Imperva_Incapsula", [("x-cdn", "incapsula"), ("server", "imperva")], ["visid_incap", "incap_ses", "nlbi_"], ["incapsula", "imperva", "_incapsula_resource"]),
    ("AWS_WAF", [("server", "awselb"), ("x-amzn-requestid", ""), ("x-amz-cf-id", "")], ["awsalb", "awsalbcors"], ["aws", "request blocked"]),
    ("F5_BigIP_ASM", [("server", "bigip"), ("x-wa-info", "")], ["bigipserver", "ts_", "f5_cspm"], ["the requested url was rejected", "support id"]),
    ("Sucuri", [("server", "sucuri"), ("x-sucuri-id", ""), ("x-sucuri-block", "")], ["sucuri_cloudproxy"], ["sucuri website firewall", "access denied - sucuri"]),
    ("Wordfence", [], ["wfwaf-authcookie"], ["wordfence", "wfwaf", "generated by wordfence"]),
    ("Barracuda", [("server", "barracuda")], ["barra_counter_session", "bni_"], ["barracuda", "web application firewall"]),
    ("Fortinet", [("server", "fortiweb"), ("fortiwafsid", "")], ["cookiesession1", "fortiwafsid"], ["fortinet", "fortiweb", "fortigate"]),
    ("Citrix_ADC", [("via", "ns-cache"), ("cneonction", ""), ("x-ns-", "")], ["citrix_ns_id", "ns_af", "nsc_"], ["citrix", "netscaler", "ns_af"]),
    ("ModSecurity", [("server", "mod_security")], ["mod_security"], ["mod_security", "modsecurity", "not acceptable", "rule id"]),
    ("DDoS-Guard", [("server", "ddos-guard")], [], ["ddos-guard"]),
]


async def fingerprint(target: str, timeout: int = 5) -> Optional[Dict[str, Any]]:
    """Attempt to fingerprint common WAFs.

    Returns a dict with keys: {"waf": name or None, "evidence": str}
    """
    if not aiohttp:
        logger.debug("aiohttp not available, cannot perform WAF fingerprinting")
        return None

    probes = ["/", "/%3Cscript%3Ealert(1)%3C/script%3E", "/admin/login"]
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}

    async with aiohttp.ClientSession() as session:
        for probe in probes:
            url = target.rstrip("/") + probe
            try:
                async with session.get(url, headers=headers, timeout=aiohttp.ClientTimeout(total=timeout), allow_redirects=True, ssl=False) as resp:
                    text = (await resp.text() or "").lower()[:5000]
                    resp_headers = {k.lower(): v.lower() for k, v in resp.headers.items()}
                    set_cookie = resp_headers.get("set-cookie", "")

                    for waf_name, header_checks, cookie_checks, body_checks in WAF_SIGNATURES:
                        score = 0
                        evidence_parts = []

                        # Check headers
                        for hdr_name, hdr_substr in header_checks:
                            val = resp_headers.get(hdr_name, "")
                            if hdr_substr == "" and hdr_name in resp_headers:
                                score += 2
                                evidence_parts.append(f"header:{hdr_name}")
                            elif hdr_substr and hdr_substr in val:
                                score += 2
                                evidence_parts.append(f"header:{hdr_name}={val[:50]}")

                        # Check cookies
                        for cookie_sig in cookie_checks:
                            if cookie_sig.lower() in set_cookie:
                                score += 2
                                evidence_parts.append(f"cookie:{cookie_sig}")

                        # Check body
                        for body_sig in body_checks:
                            if body_sig in text:
                                score += 1
                                evidence_parts.append(f"body:{body_sig}")

                        if score >= 2:
                            return {"waf": waf_name, "evidence": " | ".join(evidence_parts)}

                    # Generic WAF fallback
                    if resp.status in (403, 406, 415):
                        if any(term in text for term in ["request blocked", "access denied", "forbidden", "web application firewall"]):
                            return {"waf": "GenericWAF", "evidence": f"status:{resp.status} body_snippet:{text[:200]}"}
            except asyncio.TimeoutError:
                logger.debug(f"WAF probe timeout for {url}")
            except Exception as e:
                logger.debug(f"WAF probe error for {url}: {e}")

    return None
